### PR TITLE
Update http_build_query calls according to php 8.1

### PR DESCRIPTION
**Pull request by NikitaMelikhov**

### CODE REVIEW

**Comment by timwhitlock** [comment]
Any chance of a merge? This is only viable fork of the old SDK I can find at the moment.

**Comment by NikitaMelikhov** [comment]
Hopefully @joelbutcher will take the time to merge this request

**Review by joelbutcher — APPROVED** [review]

**Comment by timwhitlock** [comment]
Many thanks!

**Comment by NikitaMelikhov** [comment]
@joelbutcher can you make new tag for this please?

**Pull request merged**
